/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import javax.swing.JLabel;
import kontroleri.Koordinator;

/**
 *
 * @author N
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu7 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabelUlogovan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuDokumenti = new javax.swing.JMenu();
        jMenuItemEvidencijaAngazmana = new javax.swing.JMenuItem();
        jMenuPruzalacUsluge = new javax.swing.JMenu();
        jMenuItemDizajner = new javax.swing.JMenuItem();
        jMenuPrimalacUsluge = new javax.swing.JMenu();
        jMenuItemMarketingMenadzer = new javax.swing.JMenuItem();
        jMenuSifrarnici = new javax.swing.JMenu();
        jMenuItemKompanija = new javax.swing.JMenuItem();
        jMenuItemSertifikat = new javax.swing.JMenuItem();
        jMenuItemTipVizuala = new javax.swing.JMenuItem();
        jMenuPodesavanja = new javax.swing.JMenu();
        jMenuOProgramu = new javax.swing.JMenu();

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Softverski sistem za evidenciju angažmana grafičkog dizajnera");

        jLabel1.setText("Ulogovani ste kao:");

        jLabelUlogovan.setText("ulogovan");

        jMenuDokumenti.setText("Dokumenti");

        jMenuItemEvidencijaAngazmana.setText("Evidencija angažmana");
        jMenuItemEvidencijaAngazmana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEvidencijaAngazmanaActionPerformed(evt);
            }
        });
        jMenuDokumenti.add(jMenuItemEvidencijaAngazmana);

        jMenuBar1.add(jMenuDokumenti);

        jMenuPruzalacUsluge.setText("Pružalac usluge");

        jMenuItemDizajner.setText("Dizajner");
        jMenuItemDizajner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDizajnerActionPerformed(evt);
            }
        });
        jMenuPruzalacUsluge.add(jMenuItemDizajner);

        jMenuBar1.add(jMenuPruzalacUsluge);

        jMenuPrimalacUsluge.setText("Primalac usluge");

        jMenuItemMarketingMenadzer.setText("Marketing menadzer");
        jMenuItemMarketingMenadzer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarketingMenadzerActionPerformed(evt);
            }
        });
        jMenuPrimalacUsluge.add(jMenuItemMarketingMenadzer);

        jMenuBar1.add(jMenuPrimalacUsluge);

        jMenuSifrarnici.setText("Šifrarnici");

        jMenuItemKompanija.setText("Kompanija");
        jMenuItemKompanija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKompanijaActionPerformed(evt);
            }
        });
        jMenuSifrarnici.add(jMenuItemKompanija);

        jMenuItemSertifikat.setText("Serifikat");
        jMenuItemSertifikat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSertifikatActionPerformed(evt);
            }
        });
        jMenuSifrarnici.add(jMenuItemSertifikat);

        jMenuItemTipVizuala.setText("Tip vizuala");
        jMenuItemTipVizuala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTipVizualaActionPerformed(evt);
            }
        });
        jMenuSifrarnici.add(jMenuItemTipVizuala);

        jMenuBar1.add(jMenuSifrarnici);

        jMenuPodesavanja.setText("Podešavanja softverskog sistema");
        jMenuBar1.add(jMenuPodesavanja);

        jMenuOProgramu.setText("O programu");
        jMenuBar1.add(jMenuOProgramu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelUlogovan, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUlogovan)
                    .addComponent(jLabel1))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEvidencijaAngazmanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEvidencijaAngazmanaActionPerformed
        Koordinator.getInstance().otvoriEvidencijaAngazmanaFormu();
    }//GEN-LAST:event_jMenuItemEvidencijaAngazmanaActionPerformed

    private void jMenuItemDizajnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDizajnerActionPerformed
        Koordinator.getInstance().otvoriDizajnerFormu();
    }//GEN-LAST:event_jMenuItemDizajnerActionPerformed

    private void jMenuItemKompanijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKompanijaActionPerformed
        Koordinator.getInstance().otvoriKompanijaFormu();
    }//GEN-LAST:event_jMenuItemKompanijaActionPerformed

    private void jMenuItemMarketingMenadzerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarketingMenadzerActionPerformed
        Koordinator.getInstance().otvoriMarketingMenadzerFormu();
    }//GEN-LAST:event_jMenuItemMarketingMenadzerActionPerformed

    private void jMenuItemSertifikatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSertifikatActionPerformed
        Koordinator.getInstance().otvoriSertifikatFormu();
    }//GEN-LAST:event_jMenuItemSertifikatActionPerformed

    private void jMenuItemTipVizualaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTipVizualaActionPerformed
        Koordinator.getInstance().otvoriTipVizualaFormu();
    }//GEN-LAST:event_jMenuItemTipVizualaActionPerformed

    
    public JLabel getjLabelUlogovan() {
        return jLabelUlogovan;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUlogovan;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDokumenti;
    private javax.swing.JMenuItem jMenuItemDizajner;
    private javax.swing.JMenuItem jMenuItemEvidencijaAngazmana;
    private javax.swing.JMenuItem jMenuItemKompanija;
    private javax.swing.JMenuItem jMenuItemMarketingMenadzer;
    private javax.swing.JMenuItem jMenuItemSertifikat;
    private javax.swing.JMenuItem jMenuItemTipVizuala;
    private javax.swing.JMenu jMenuOProgramu;
    private javax.swing.JMenu jMenuPodesavanja;
    private javax.swing.JMenu jMenuPrimalacUsluge;
    private javax.swing.JMenu jMenuPruzalacUsluge;
    private javax.swing.JMenu jMenuSifrarnici;
    // End of variables declaration//GEN-END:variables
}
