/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import javax.swing.JLabel;
import kontroleri.Koordinator;

/**
 *
 * @author N
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu7 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabelUlogovan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuDokumenti = new javax.swing.JMenu();
        jMenuItemEvidencijaAngazmana = new javax.swing.JMenuItem();
        jMenuPruzalacUsluge = new javax.swing.JMenu();
        jMenuItemDizajner = new javax.swing.JMenuItem();
        jMenuPrimalacUsluge = new javax.swing.JMenu();
        jMenuItemMarketingMenadzer = new javax.swing.JMenuItem();
        jMenuSifrarnici = new javax.swing.JMenu();
        jMenuItemKompanija = new javax.swing.JMenuItem();
        jMenuItemSertifikat = new javax.swing.JMenuItem();
        jMenuItemTipVizuala = new javax.swing.JMenuItem();
        jMenuPodesavanja = new javax.swing.JMenu();
        jMenuOProgramu = new javax.swing.JMenu();

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ulogovani ste kao:");

        jLabelUlogovan.setText("ulogovan");

        jMenuDokumenti.setText("Dokumenti");

        jMenuItemEvidencijaAngazmana.setText("Evidencija angažmana");
        jMenuItemEvidencijaAngazmana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEvidencijaAngazmanaActionPerformed(evt);
            }
        });
        jMenuDokumenti.add(jMenuItemEvidencijaAngazmana);

        jMenuBar1.add(jMenuDokumenti);

        jMenuPruzalacUsluge.setText("Pružalac usluge");

        jMenuItemDizajner.setText("Dizajner");
        jMenuItemDizajner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDizajnerActionPerformed(evt);
            }
        });
        jMenuPruzalacUsluge.add(jMenuItemDizajner);

        jMenuBar1.add(jMenuPruzalacUsluge);

        jMenuPrimalacUsluge.setText("Primalac usluge");

        jMenuItemMarketingMenadzer.setText("Marketing menadzer");
        jMenuPrimalacUsluge.add(jMenuItemMarketingMenadzer);

        jMenuBar1.add(jMenuPrimalacUsluge);

        jMenuSifrarnici.setText("Šifrarnici");

        jMenuItemKompanija.setText("Kompanija");
        jMenuSifrarnici.add(jMenuItemKompanija);

        jMenuItemSertifikat.setText("Serifikat");
        jMenuSifrarnici.add(jMenuItemSertifikat);

        jMenuItemTipVizuala.setText("Tip vizuala");
        jMenuSifrarnici.add(jMenuItemTipVizuala);

        jMenuBar1.add(jMenuSifrarnici);

        jMenuPodesavanja.setText("Podešavanja softverskog sistema");
        jMenuBar1.add(jMenuPodesavanja);

        jMenuOProgramu.setText("O programu");
        jMenuBar1.add(jMenuOProgramu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelUlogovan, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUlogovan)
                    .addComponent(jLabel1))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEvidencijaAngazmanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEvidencijaAngazmanaActionPerformed
        EvidencijaAngazmanaForma eaf= new EvidencijaAngazmanaForma();
        eaf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemEvidencijaAngazmanaActionPerformed

    private void jMenuItemDizajnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDizajnerActionPerformed
        Koordinator.getInstance().otvoriDizajnerFormu();
        this.dispose();
    }//GEN-LAST:event_jMenuItemDizajnerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    public JLabel getjLabelUlogovan() {
        return jLabelUlogovan;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUlogovan;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDokumenti;
    private javax.swing.JMenuItem jMenuItemDizajner;
    private javax.swing.JMenuItem jMenuItemEvidencijaAngazmana;
    private javax.swing.JMenuItem jMenuItemKompanija;
    private javax.swing.JMenuItem jMenuItemMarketingMenadzer;
    private javax.swing.JMenuItem jMenuItemSertifikat;
    private javax.swing.JMenuItem jMenuItemTipVizuala;
    private javax.swing.JMenu jMenuOProgramu;
    private javax.swing.JMenu jMenuPodesavanja;
    private javax.swing.JMenu jMenuPrimalacUsluge;
    private javax.swing.JMenu jMenuPruzalacUsluge;
    private javax.swing.JMenu jMenuSifrarnici;
    // End of variables declaration//GEN-END:variables
}
