/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.event.ActionListener;
import javax.swing.JTable;

/**
 *
 * @author N
 */
public class SertifikatForma extends javax.swing.JFrame {

    /**
     * Creates new form KompanijaForma
     */
    public SertifikatForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSertifikat = new javax.swing.JTable();
        jButtonUbaci = new javax.swing.JButton();
        jButtonGF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sertifikat");
        setName("Sertifikat"); // NOI18N

        jTableSertifikat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSertifikat);

        jButtonUbaci.setText("Ubaci sertifikat");
        jButtonUbaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbaciActionPerformed(evt);
            }
        });

        jButtonGF.setText("Glavna forma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButtonUbaci, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jButtonGF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUbaci)
                    .addComponent(jButtonGF))
                .addGap(113, 113, 113))
        );

        getAccessibleContext().setAccessibleName("Sertifikat");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUbaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbaciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUbaciActionPerformed

    
    

    public JTable getjTableSertifikat() {
        return jTableSertifikat;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGF;
    private javax.swing.JButton jButtonUbaci;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSertifikat;
    // End of variables declaration//GEN-END:variables

    
    
    public void addButtonUbaciActionListener(ActionListener actionListener) {
        jButtonUbaci.addActionListener(actionListener);
    }
    
    
    
    public void addButtonGFActionListener(ActionListener actionListener) {
        jButtonGF.addActionListener(actionListener);
    }
}
