/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package komunikacija;

import java.io.Serializable;

/**
 *
 * @author N
 */
public enum Operacija implements Serializable {
    PRIJAVI_DIZAJNER, 
    VRATI_LISTU_SVI_DIZAJNER,
    OBRISI_DIZAJNER,
    KREIRAJ_DIZAJNER,
    PROMENI_DIZAJNER, 
    VRATI_LISTU_SVI_KOMPANIJA,
    KREIRAJ_KOMPANIJA,
    PROMENI_KOMPANIJA,
    OBRISI_KOMPANIJA,
    VRATI_LISTU_SVI_MARKETING_MENADZER,
    PRETRAZI_MARKETING_MENADZER,
    OBRISI_MARKETING_MENADZER,
    KREIRAJ_MARKETING_MENADZER,
    PROMENI_MARKETING_MENADZER,
    UCITAJ_MARKETING_MENADZER,
    VRATI_LISTU_SVI_SERTIFIKAT,
    UBACI_SERTIFIKAT,
    VRATI_LISTU_SVI_TIP_VIZUALA,
    VRATI_LISTU_SVI_EVIDENCIJA_ANGAZMANA,
    PRETRAZI_EVIDENCIJA_ANGAZMANA,
    OBRISI_EVIDENCIJA_ANGAZMANA,
    PROMENI_EVIDENCIJA_ANGAZMANA,
    KREIRAJ_EVIDENCIJA_ANGAZMANA,
    UCITAJ_EVIDENCIJA_ANGAZMANA
}
